### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by mdeff** [mdeff/ntds_2019#6]
- [x] September 28: installation & introduction (#1), @mdeff
- [x] October 2: assignment 1 (#6), @bayrameda and @Stalence
- [x] October 2: graph construction tutorial (#5), @bricaud
- [x] October 8: NetworkX tutorial (#7), @ersisimou
- [x] October: dataset ideas (#4), all
- [x] October 23: assignment 2 (#10), @cvignac and @gortizji
- [x] October 29: scikit-learn tutorial (#9), @naspert
- [ ] November 6: pytorch tutorial, @naspert
- [x] November 6: project grading sheet (#11), all
- [x] November 6: project expectations and organization (#12), @mdeff
- [x] November: solution, grades, and feedback for assignment 1 (#3), @bayrameda and @Stalence
- [x] November: pygsp tutorial (#16)
- [x] December 4: visualization tutorial (#13), @mizvol
- [x] December 5: add project summaries (#15), @mdeff 
- [x] December: solution, grades, and feedback for assignment 2 (#8, mdeff/ntds_2019_private#14), @cvignac and @gortizji
- [x] January 11: add project reports and repository links (#17), @mdeff
- [x] January 25: add project slides (#18), @mdeff
